services:
  - type: web
    name: questionario-back
    env: docker
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
      - key: SPRING_DATASOURCE_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
      - key: API_SECRET_KEY
      - key: GEMINI_API_KEY
      - key: SPRING_MAIL_USERNAME
      - key: SPRING_MAIL_PASSWORD